parameters:
#    logan_message.example.class: Logan\MessageBundle\Example

services:
   message:
      class: Logan\MessageBundle\Entity\Message

   messageType:
      class:  Logan\MessageBundle\Form\MessageType

   messageRepository:
       class: Symfony\Bundle\FrameworkBundle\Controller
       factory_service: doctrine
       factory_method: getRepository
       arguments:
           - 'LoganMessageBundle:Message'
