parameters:
#    logan_message.example.class: Logan\MessageBundle\Example

services:
   message:
      class: Logan\MessageBundle\Entity\Message

   messageType:
      class:  Logan\MessageBundle\Form\MessageType
