# app/config/security.yml
security:
    encoders:
        Logan\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: LoganUserBundle:User, property: username }

    firewalls:
        login_firewall:
                pattern:   ^/login$
                anonymous: ~
        registration:
                pattern:   ^/register
                anonymous: ~
        secured_area:
            pattern:    ^/
            form_login:
                  login_path: /login
                  check_path: /login_check
            logout: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
