parameters:
#    logan_user.example.class: Logan\UserBundle\Example

services:
   user:
      class: Logan\UserBundle\Entity\User

   userType:
      class: Logan\UserBundle\Form\Type\UserType

   userRepository:
       class: Symfony\Bundle\FrameworkBundle\Controller
       factory_service: doctrine
       factory_method: getRepository
       arguments:
           - 'LoganUserBundle:User'